### ISSUE TITLE
Integrate Client Documentation standard

### ISSUE THREAD

**Issue by cfilby** [WBHM-ORG/mobile-player#11]
Should we look into integrating ngdocs?

**Comment by scrudge** [comment]
It would seem to be the logical choice.

Also, any suggestions for the API, http://www.phpdoc.org/?

**Comment by cfilby** [comment]
Are you looking for internal documentation, or REST API documentation?

**Comment by scrudge** [comment]
Both.  I'm thinking phpDoc for internal.  It's a wordpress standard.  But it's probably not the best for the api.

**Comment by cfilby** [comment]
Definitely agree on phpDoc for internal documentation. As far as API goes, there's a wealth of options. Swagger is pretty popular, APIDoc is also pretty straightforward.
